### ISSUE TITLE
Setup CI/CD with testing and auto-deployment to Chrome/Edge stores

### ISSUE THREAD

**Issue by icedac** [icedac/relaxblock#4]
## Description
Implement comprehensive CI/CD pipeline with automated testing, linting, and deployment to Chrome Web Store and Microsoft Edge Add-ons store when code is merged to main branch.

### 1. Continuous Integration
- **Unit Tests**: Jest test suite with coverage reporting
- **Linting**: ESLint with browser extension best practices
- **E2E Tests**: Puppeteer tests for extension functionality
- **Build Validation**: Ensure extension builds correctly
- **Manifest Validation**: Validate manifest.json structure

### 2. Continuous Deployment
- Auto-deploy to Chrome Web Store on main branch merge
- Auto-deploy to Microsoft Edge Add-ons store on main branch merge
- Version bumping automation
- Release notes generation

#### 1. CI Pipeline (`.github/workflows/ci.yml`)
```yaml
name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@v3

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run test:e2e
```

#### 2. CD Pipeline (`.github/workflows/deploy.yml`)
```yaml
name: Deploy to Stores
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      
      # Version bump
      - name: Bump version
        run: npm version patch
      
      # Deploy to Chrome Web Store
      - name: Deploy to Chrome Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.CHROME_EXTENSION_ID }}
          zip: build/relaxblock.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      
      # Deploy to Edge Add-ons
      - name: Deploy to Edge Store
        uses: wdzeng/edge-addon@v1
        with:
          product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          zip-path: build/relaxblock.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
```

### 3. Required npm Scripts
```json
{
  "scripts": {
    "test": "jest",
    "test:e2e": "jest --config=jest.e2e.config.js",
    "lint": "eslint . --ext .js",
    "lint:fix": "eslint . --ext .js --fix",
    "build": "npm run lint && npm test && npm run package",
    "package": "zip -r build/relaxblock.zip . -x '*.git*' 'node_modules/*' 'test/*' '*.md' 'package*.json'"
  }
}
```

### 4. ESLint Configuration
```javascript
// .eslintrc.js
module.exports = {
  env: {
    browser: true,
    webextensions: true,
    es2021: true
  },
  extends: ['eslint:recommended'],
  rules: {
    'no-console': 'warn',
    'no-unused-vars': 'error',
    'prefer-const': 'error'
  }
};
```

### 5. Puppeteer E2E Tests
```javascript
// test/e2e/extension.test.js
describe('RelaxBlock Extension E2E', () => {
  test('should block configured domains', async () => {
    // Load extension
    // Navigate to blocked domain
    // Verify grayscale and overlay
  });
  
  test('should activate relax mode', async () => {
    // Click relax button
    // Verify timer starts
    // Verify site is accessible
  });
});
```

### 6. Store Credentials Setup
Required GitHub Secrets:
- `CHROME_EXTENSION_ID`
- `CHROME_CLIENT_ID`
- `CHROME_CLIENT_SECRET`
- `CHROME_REFRESH_TOKEN`
- `EDGE_PRODUCT_ID`
- `EDGE_CLIENT_ID`
- `EDGE_CLIENT_SECRET`
- `EDGE_ACCESS_TOKEN_URL`

## Acceptance Criteria
- [ ] All tests pass before deployment
- [ ] ESLint configured with no errors
- [ ] Puppeteer E2E tests cover main functionality
- [ ] Automatic version bumping works
- [ ] Chrome Web Store deployment succeeds
- [ ] Edge Add-ons deployment succeeds
- [ ] Build artifacts are properly generated
- [ ] Coverage reports are generated

## Test Plan
1. Create PR and verify CI checks run
2. Merge PR and verify deployment triggers
3. Check Chrome Web Store for updated version
4. Check Edge Add-ons for updated version
5. Verify version number incremented correctly
6. Test rollback procedure if deployment fails
